# Generated by Django 3.2.5 on 2021-12-20 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lposts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='post',
            name='img_link',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='post',
            name='scraped_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
